restaurant/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('waimai.urls')), 
     path('admin/', admin.site.urls),
]

waimai/urls.py
from django.urls import path

from . import views
app_name = 'waimai'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

waimai/models.py
from django.db import models

# Create your models here.

waimai/views.py
from django.shortcuts import render

def home_page(request):

    if request.method == 'POST':
        order = request.POST.get('order')
        address = request.POST.get("address")

        print(order * 10)
        return render(request, 'waimai/home_page.html', {'address': address, 'order': order})

    return render(request, 'waimai/home_page.html')

waimai/templates/waimai/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Prince Benson Waimai</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Prince Benson Fusion Restaurant</h1>

<!-- Blog Post -->
 <h2>Tasty Treats To Your Door</h2>
 <p>No.1 Tasty Pizza! $10</p>
 <p><img src="http://r.photo.store.qq.com/psb?/V11qtBa523MrFv/fwWoldDNo6MJ1V3vUEUaDblQ0fkn7uL7cFhNgd.0ezI!/r/dEABAAAAAAAA"></p>
 <p>No.2 Huge burger! $5</p>
 <p><img src="http://r.photo.store.qq.com/psb?/V11qtBa523MrFv/frkol5xEeUTPG0Oqo.qPPkK3Z8rf0Zvtd8Bq4mCc3iM!/r/dGcBAAAAAAAA"></p>
 <p>No.3 Healthy Salad! $5</p>
 <p><img src=" http://r.photo.store.qq.com/psb?/V11qtBa523MrFv/TCr..VPIn6ZWymsOz9HTyyj2YmoV*Jnz5Trq.F31gFA!/r/dEIBAAAAAAAA
"></p>

<!-- Like And Comment -->
 <button>Tasty</button>
 <h2>Order Some Food: </h2>
 <form action="{% url 'waimai:home_page' %}" method="POST">
 {% csrf_token %}
 <textarea name="address" placeholder="Please Enter Your Address"></textarea><br>
 <input type="text" placeholder="Please Enter Your Order" name="order"><br><br>
 <input type="submit" value="Order Now!">
 </form>

<h2>Orders: </h2>
 Address {{address}} Orders: {{order}}
</body>
</html>